version: "3.9"
services:
  backend:
    image: docker.io/tomazdimas/chatbot-backend:v2
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
  frontend:
    build: ./app/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  redis:
    image: redis/redis-stack:7.2.0-v10
    ports:
      - "6379:6379"
      - "8001:8001" # painel RedisInsight
