services:
  redis:
    image: redis/redis-stack:7.2.0-v10
    ports:
      - "6380:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes

volumes:
  redis-data:
